server:
  port: 8080

spring:
  application:
    name: gateway-service

  data:
    redis:
      port: 6379
      host: localhost

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            - id: menuservice
              uri: lb://menuservice
              predicates:
                - Path=/api/restaurant/**
            - id: inventoryservice
              uri: lb://inventoryservice
              predicates:
                - Path=/api/inventory/**

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:5173"
                  - "http://localhost:5174"
                  - "http://localhost:3000"
                allowedMethods: "*"
                allowedHeaders: "*"
                allowCredentials: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
