version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.2
    container_name: keycloak-26.4.2
    ports:
      - "8180:8080"
    networks:
      - default
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: dev-mem
    command: ["start-dev"]
networks:
  default:
    driver: bridge